org.gradle.daemon=false
org.gradle.jvmargs=-Xmx4G
org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.parallel=false
net.minecraftforge.gradle.merge-source-sets=false

mod_group=zone.moddev.mc.mmdlib
mod_version=1.0.0.112021
minecraft_version=1.12.2
loader_name=forge
loader_code=1
java_version=8
java_toolchain_version=8.0.502+7
java_setup_version=8.0.502+7
gradle_java_version=17
mavenizer_java_version=25.0.3+9
forge_version=14.23.5.2847
mappings_channel=stable
mappings_version=39-1.12
curseforge_project_id=261744
cf_project_id=261744
cf_release_type=beta
cf_changelog_filename=CHANGELOG.txt
cf_changelog_type=text
cf_versions=1.12.2
cf_requirements=
cf_optionals=mmd-orespawn,additional-loot-tables
forge_installer_sha256=3A74473FC62DCF13BAA4130E6EA31A80C6A872B6B25F1A4C9195C8E878415BD0
forge_compat_version=14.23.5.2859
forge_compat_installer_sha256=DBBA1CD1BF34A4B82148BAC50A6150F63FFCB2D5DC7D88A0508C27FDCFF15B76
