@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.mcmoddev.lib.container.slots;

import javax.annotation.ParametersAreNonnullByDefault;
import mcp.MethodsReturnNonnullByDefault;