@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.mcmoddev.lib.container.slot;

import javax.annotation.ParametersAreNonnullByDefault;
import mcp.MethodsReturnNonnullByDefault;